version: 2

jobs:
  checkout:
    working_directory: ~/openfisca-tunisia
    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout

      - run:
          name: Fetch remote refs
          command: git fetch

      - save_cache:
          key: v1-checkout-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .
            - ~/.ssh/known_hosts

  dependencies:
    working_directory: ~/openfisca-tunisia
    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - restore_cache:
          keys:
            - v1-checkout-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Create virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-tunisia
            virtualenv /tmp/venv/openfisca-tunisia

      # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
      - run:
          name: Install dependencies
          command: |
            . /tmp/venv/openfisca-tunisia/bin/activate
            pip install --upgrade pip wheel twine
            pip install .[tests,notebook] --upgrade

      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /tmp/venv/openfisca-tunisia

  tests:
    working_directory: ~/openfisca-tunisia
    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - restore_cache:
          keys:
            - v1-checkout-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Run tests
          command: |
            . /tmp/venv/openfisca-tunisia/bin/activate
            make test
            . check-version-bump.sh

  deploy:
    working_directory: ~/openfisca-tunisia
    docker:
      - image: circleci/python:2.7-jessie
        environment:
          PYPI_USERNAME: openfisca-bot
          # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - restore_cache:
          keys:
            - v1-checkout-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Deploy (if version bump)
          command: |
            . /tmp/venv/openfisca-tunisia/bin/activate
            . deploy-if-version-bump.sh

workflows:
  version: 2
  openfisca-tunisia:
    jobs:
      - checkout

      - dependencies:
          requires:
            - checkout

      - tests:
          requires:
            - dependencies

      - deploy:
          requires:
            - tests
          filters:
            branches:
              only: master
